In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, roc_auc_score, classification_report
from sklearn.metrics import mean_squared_error

In [ ]:
lona_17=pd.read_excel('/content/drive/MyDrive/Colab/loan project/loan_2017.xlsx')

In [ ]:
loan_18=pd.read_excel('/content/drive/MyDrive/Colab/loan project/loan_2018.xlsx')

In [ ]:
loan_17=lona_17

In [ ]:
loan_17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88341 entries, 0 to 88340
Data columns (total 98 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              88341 non-null  int64
 1   loan_amnt                       88341 non-null  int64
 2   term_months                     88341 non-null  int64
 3   installment                     88341 non-null  float64
 4   sub_grade                       88341 non-null  object
 5   emp_length                      82254 non-null  float64
 6   home_ownership                  88341 non-null  object
 7   annual_inc                      88341 non-null  float64
 8   verification_status             88341 non-null  object
 9   loan_status                     88341 non-null  int64
 10  purpose                         88341 non-null  object
 11  addr_state                      88341 non-null  object
 12  dti                             88239 non-null  float64
 13  delinq_2yrs                     88341 non-null  int64
 14  inq_last_6mths                  88341 non-null  int64
 15  mths_since_last_delinq          45128 non-null  float64
 16  mths_since_last_record          17162 non-null  float64
 17  open_acc                        88341 non-null  int64
 18  pub_rec                         88341 non-null  int64
 19  revol_bal                       88341 non-null  int64
 20  revol_util                      88272 non-null  float64
 21  total_acc                       88341 non-null  int64
 22  initial_list_status             88341 non-null  object
 23  out_prncp                       88341 non-null  float64
 24  total_pymnt                     88341 non-null  float64
 25  total_rec_prncp                 88341 non-null  float64
 26  total_rec_int                   88341 non-null  float64
 27  total_rec_late_fee              88341 non-null  float64
 28  recoveries                      88341 non-null  float64
 29  collection_recovery_fee         88341 non-null  float64
 30  last_pymnt_amnt                 88341 non-null  float64
 31  collections_12_mths_ex_med      88341 non-null  int64
 32  mths_since_last_major_derog     24896 non-null  float64
 33  application_type                88341 non-null  object
 34  acc_now_delinq                  88341 non-null  int64
 35  tot_coll_amt                    88341 non-null  int64
 36  tot_cur_bal                     88341 non-null  int64
 37  open_acc_6m                     88341 non-null  int64
 38  open_act_il                     88341 non-null  int64
 39  open_il_12m                     88341 non-null  int64
 40  open_il_24m                     88341 non-null  int64
 41  mths_since_rcnt_il              86176 non-null  float64
 42  total_bal_il                    88341 non-null  int64
 43  il_util                         76830 non-null  float64
 44  open_rv_12m                     88341 non-null  int64
 45  open_rv_24m                     88341 non-null  int64
 46  max_bal_bc                      88341 non-null  int64
 47  all_util                        88331 non-null  float64
 48  total_rev_hi_lim                88341 non-null  int64
 49  inq_fi                          88341 non-null  int64
 50  total_cu_tl                     88341 non-null  int64
 51  inq_last_12m                    88341 non-null  int64
 52  acc_open_past_24mths            88341 non-null  int64
 53  avg_cur_bal                     88339 non-null  float64
 54  bc_open_to_buy                  87206 non-null  float64
 55  bc_util                         87160 non-null  float64
 56  chargeoff_within_12_mths        88341 non-null  int64
 57  delinq_amnt                     88341 non-null  int64
 58  mo_sin_old_il_acct              86176 non-null  float64
 59  mo_sin_old_rev_tl_op            88341 non-null  int64
 60  mo_sin_rcnt_rev_tl_op           88341 non-null  int64
 61  mo_sin_rcnt_tl                  88341 non-null  int64
 62  mort_acc                        88341 non-null  int64
 63  mths_since_recent_bc            87268 non-null  float64
 64  mths_since_recent_bc_dlq        21093 non-null  float64
 65  mths_since_recent_inq           80506 non-null  float64
 66  mths_since_recent_revol_delinq  30582 non-null  float64
 67  num_accts_ever_120_pd           88341 non-null  int64
 68  num_actv_bc_tl                  88341 non-null  int64
 69  num_actv_rev_tl                 88341 non-null  int64
 70  num_bc_sats                     88341 non-null  int64
 71  num_bc_tl                       88341 non-null  int64
 72  num_il_tl                       88341 non-null  int64
 73  num_op_rev_tl                   88341 non-null  int64
 74  num_rev_accts                   88341 non-null  int64
 75  num_rev_tl_bal_gt_0             88341 non-null  int64
 76  num_sats                        88341 non-null  int64
 77  num_tl_120dpd_2m                84017 non-null  float64
 78  num_tl_30dpd                    88341 non-null  int64
 79  num_tl_90g_dpd_24m              88341 non-null  int64
 80  num_tl_op_past_12m              88341 non-null  int64
 81  pct_tl_nvr_dlq                  88341 non-null  float64
 82  percent_bc_gt_75                87204 non-null  float64
 83  pub_rec_bankruptcies            88341 non-null  int64
 84  tax_liens                       88341 non-null  int64
 85  tot_hi_cred_lim                 88341 non-null  int64
 86  total_bal_ex_mort               88341 non-null  int64
 87  total_bc_limit                  88341 non-null  int64
 88  total_il_high_credit_limit      88341 non-null  int64
 89  disbursement_method             88341 non-null  object
 90  debt_settlement_flag            88341 non-null  object
 91  issue_year                      88341 non-null  int64
 92  issue_month                     88341 non-null  int64
 93  fico_score                      88341 non-null  float64
 94  last_fico_score                 88341 non-null  float64
 95  earliest_cr_line_year           88341 non-null  int64
 96  earliest_cr_line_month          88341 non-null  int64
 97  credit_history_years            88341 non-null  int64
dtypes: float64(32), int64(57), object(9)
memory usage: 66.1+ MB

In [ ]:
loan_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32834 entries, 0 to 32833
Data columns (total 98 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              32834 non-null  int64
 1   loan_amnt                       32834 non-null  int64
 2   term_months                     32834 non-null  int64
 3   installment                     32834 non-null  float64
 4   sub_grade                       32834 non-null  object
 5   emp_length                      29968 non-null  float64
 6   home_ownership                  32834 non-null  object
 7   annual_inc                      32834 non-null  float64
 8   verification_status             32834 non-null  object
 9   loan_status                     32834 non-null  int64
 10  purpose                         32834 non-null  object
 11  addr_state                      32834 non-null  object
 12  dti                             32738 non-null  float64
 13  delinq_2yrs                     32834 non-null  int64
 14  inq_last_6mths                  32834 non-null  int64
 15  mths_since_last_delinq          14670 non-null  float64
 16  mths_since_last_record          5027 non-null   float64
 17  open_acc                        32834 non-null  int64
 18  pub_rec                         32834 non-null  int64
 19  revol_bal                       32834 non-null  int64
 20  revol_util                      32796 non-null  float64
 21  total_acc                       32834 non-null  int64
 22  initial_list_status             32834 non-null  object
 23  out_prncp                       32834 non-null  float64
 24  total_pymnt                     32834 non-null  float64
 25  total_rec_prncp                 32834 non-null  float64
 26  total_rec_int                   32834 non-null  float64
 27  total_rec_late_fee              32834 non-null  float64
 28  recoveries                      32834 non-null  float64
 29  collection_recovery_fee         32834 non-null  float64
 30  last_pymnt_amnt                 32834 non-null  float64
 31  collections_12_mths_ex_med      32834 non-null  int64
 32  mths_since_last_major_derog     7927 non-null   float64
 33  application_type                32834 non-null  object
 34  acc_now_delinq                  32834 non-null  int64
 35  tot_coll_amt                    32834 non-null  int64
 36  tot_cur_bal                     32834 non-null  int64
 37  open_acc_6m                     32834 non-null  int64
 38  open_act_il                     32834 non-null  int64
 39  open_il_12m                     32834 non-null  int64
 40  open_il_24m                     32834 non-null  int64
 41  mths_since_rcnt_il              31709 non-null  float64
 42  total_bal_il                    32834 non-null  int64
 43  il_util                         27352 non-null  float64
 44  open_rv_12m                     32834 non-null  int64
 45  open_rv_24m                     32834 non-null  int64
 46  max_bal_bc                      32834 non-null  int64
 47  all_util                        32825 non-null  float64
 48  total_rev_hi_lim                32834 non-null  int64
 49  inq_fi                          32834 non-null  int64
 50  total_cu_tl                     32834 non-null  int64
 51  inq_last_12m                    32834 non-null  int64
 52  acc_open_past_24mths            32834 non-null  int64
 53  avg_cur_bal                     32831 non-null  float64
 54  bc_open_to_buy                  32296 non-null  float64
 55  bc_util                         32278 non-null  float64
 56  chargeoff_within_12_mths        32834 non-null  int64
 57  delinq_amnt                     32834 non-null  int64
 58  mo_sin_old_il_acct              31709 non-null  float64
 59  mo_sin_old_rev_tl_op            32834 non-null  int64
 60  mo_sin_rcnt_rev_tl_op           32834 non-null  int64
 61  mo_sin_rcnt_tl                  32834 non-null  int64
 62  mort_acc                        32834 non-null  int64
 63  mths_since_recent_bc            32338 non-null  float64
 64  mths_since_recent_bc_dlq        6830 non-null   float64
 65  mths_since_recent_inq           30046 non-null  float64
 66  mths_since_recent_revol_delinq  9757 non-null   float64
 67  num_accts_ever_120_pd           32834 non-null  int64
 68  num_actv_bc_tl                  32834 non-null  int64
 69  num_actv_rev_tl                 32834 non-null  int64
 70  num_bc_sats                     32834 non-null  int64
 71  num_bc_tl                       32834 non-null  int64
 72  num_il_tl                       32834 non-null  int64
 73  num_op_rev_tl                   32834 non-null  int64
 74  num_rev_accts                   32834 non-null  int64
 75  num_rev_tl_bal_gt_0             32834 non-null  int64
 76  num_sats                        32834 non-null  int64
 77  num_tl_120dpd_2m                31863 non-null  float64
 78  num_tl_30dpd                    32834 non-null  int64
 79  num_tl_90g_dpd_24m              32834 non-null  int64
 80  num_tl_op_past_12m              32834 non-null  int64
 81  pct_tl_nvr_dlq                  32833 non-null  float64
 82  percent_bc_gt_75                32295 non-null  float64
 83  pub_rec_bankruptcies            32834 non-null  int64
 84  tax_liens                       32834 non-null  int64
 85  tot_hi_cred_lim                 32834 non-null  int64
 86  total_bal_ex_mort               32834 non-null  int64
 87  total_bc_limit                  32834 non-null  int64
 88  total_il_high_credit_limit      32834 non-null  int64
 89  disbursement_method             32834 non-null  object
 90  debt_settlement_flag            32834 non-null  object
 91  issue_year                      32834 non-null  int64
 92  issue_month                     32834 non-null  int64
 93  fico_score                      32834 non-null  float64
 94  last_fico_score                 32834 non-null  float64
 95  earliest_cr_line_year           32834 non-null  int64
 96  earliest_cr_line_month          32834 non-null  int64
 97  credit_history_years            32834 non-null  int64
dtypes: float64(32), int64(57), object(9)
memory usage: 24.5+ MB

In [ ]:
loan_17.describe().T

,count,mean,std,min,25%,50%,75%,max
id,88341.0,1.117999e+08,4.842603e+06,687119.00,1.082242e+08,1.117355e+08,1.153894e+08,1.201227e+08
loan_amnt,88341.0,1.408882e+04,9.390212e+03,1000.00,6.900000e+03,1.200000e+04,2.000000e+04,4.000000e+04
term_months,88341.0,4.177499e+01,1.025916e+01,36.00,3.600000e+01,3.600000e+01,3.600000e+01,6.000000e+01
installment,88341.0,4.341615e+02,2.885249e+02,30.12,2.233400e+02,3.539500e+02,5.812800e+02,1.719830e+03
emp_length,82254.0,5.798599e+00,3.789068e+00,0.00,2.000000e+00,6.000000e+00,1.000000e+01,1.000000e+01
...,...,...,...,...,...,...,...,...
fico_score,88341.0,7.003709e+02,3.401585e+01,662.00,6.720000e+02,6.920000e+02,7.170000e+02,8.475000e+02
last_fico_score,88341.0,6.652547e+02,1.063408e+02,249.50,6.270000e+02,6.920000e+02,7.270000e+02,8.475000e+02
earliest_cr_line_year,88341.0,2.001093e+03,7.903732e+00,1969.00,1.997000e+03,2.003000e+03,2.006000e+03,2.068000e+03
earliest_cr_line_month,88341.0,6.736080e+00,3.371426e+00,1.00,4.000000e+00,7.000000e+00,1.000000e+01,1.200000e+01
credit_history_years,88341.0,1.539825e+01,7.887489e+00,-51.00,1.100000e+01,1.400000e+01,1.900000e+01,4.800000e+01

In [ ]:
loan_18.describe().T

,count,mean,std,min,25%,50%,75%,max
id,32834.0,1.313867e+08,4.745877e+06,70102325.00,1.276395e+08,1.294088e+08,1.365741e+08,1.411120e+08
loan_amnt,32834.0,1.501008e+04,1.010961e+04,1000.00,7.000000e+03,1.200000e+04,2.000000e+04,4.000000e+04
term_months,32834.0,4.243747e+01,1.063305e+01,36.00,3.600000e+01,3.600000e+01,6.000000e+01,6.000000e+01
installment,32834.0,4.485800e+02,2.929118e+02,30.12,2.272600e+02,3.664200e+02,6.149900e+02,1.587230e+03
emp_length,29968.0,5.916478e+00,3.722182e+00,0.00,2.000000e+00,6.000000e+00,1.000000e+01,1.000000e+01
...,...,...,...,...,...,...,...,...
fico_score,32834.0,7.104456e+02,3.794853e+01,662.00,6.820000e+02,7.020000e+02,7.320000e+02,8.475000e+02
last_fico_score,32834.0,6.869126e+02,9.563176e+01,0.00,6.670000e+02,7.070000e+02,7.420000e+02,8.475000e+02
earliest_cr_line_year,32834.0,2.001899e+03,7.958023e+00,1969.00,1.998000e+03,2.003000e+03,2.007000e+03,2.068000e+03
earliest_cr_line_month,32834.0,6.743985e+00,3.368946e+00,1.00,4.000000e+00,7.000000e+00,1.000000e+01,1.200000e+01
credit_history_years,32834.0,1.536328e+01,7.940334e+00,-50.00,1.100000e+01,1.400000e+01,1.900000e+01,4.900000e+01

In [ ]:
loan_17["credit_history_years"].value_counts()

credit_history_years
12    7690
11    6953
10    6051
13    5711
14    5678
15    4950
16    4837
17    3745
18    3552
9     3294
19    2923
20    2877
21    2426
8     2335
22    2259
6     2020
23    1991
7     1943
4     1851
5     1818
24    1558
3     1413
27    1203
26    1194
28    1100
25    1074
30     868
29     812
31     672
32     617
33     449
34     413
35     312
36     232
38     220
39     203
37     191
40     175
41     131
44     106
42     103
43      81
47      68
48      56
46      54
45      53
50      32
51      30
49      17
Name: count, dtype: int64

In [ ]:
loan_18['credit_history_years'] = loan_18['credit_history_years'].abs()
loan_17['credit_history_years'] = loan_17['credit_history_years'].abs()

In [ ]:
loan_18["dti"].describe()

count    32738.000000
mean        18.577039
std         18.311968
min          0.000000
25%         10.430000
50%         16.830000
75%         24.020000
max        999.000000
Name: dti, dtype: float64

In [ ]:
loan=pd.read_excel('/content/drive/MyDrive/Colab/loan project/loan5.xlsx')

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121175 entries, 0 to 121174
Columns: 119 entries, id to credit_history_years
dtypes: float64(50), int64(56), object(13)
memory usage: 110.0+ MB

In [ ]:
loan

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,settlement_amount,settlement_percentage,settlement_term,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,Scale Technician,9.0,RENT,52000.0,...,NaN,NaN,NaN,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,SDO Supervisor,10.0,OWN,55000.0,...,NaN,NaN,NaN,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,Parole,0.0,MORTGAGE,40000.0,...,NaN,NaN,NaN,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,teacher,10.0,OWN,57000.0,...,NaN,NaN,NaN,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,Machine operator,10.0,OWN,85000.0,...,NaN,NaN,NaN,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,102395624,35000,60 months,13.99,814.21,C3,Industrial Engineer,0.0,MORTGAGE,100000.0,...,NaN,NaN,NaN,2017,4,687.0,772.0,1996,5,20
121171,102426796,12000,60 months,28.69,378.65,F1,foreman,10.0,MORTGAGE,64500.0,...,NaN,NaN,NaN,2017,4,662.0,712.0,2005,11,11
121172,102556443,24000,60 months,23.99,690.30,E2,Senior Escrow Officer,0.0,RENT,107000.0,...,NaN,NaN,NaN,2017,4,672.0,249.5,1995,4,22
121173,102196576,6000,36 months,11.44,197.69,B4,Contact input,5.0,RENT,41000.0,...,NaN,NaN,NaN,2017,4,672.0,717.0,1990,5,26
121174,99799684,30000,60 months,25.49,889.18,E4,Assistant Manager,4.0,MORTGAGE,105700.0,...,NaN,NaN,NaN,2017,4,697.0,577.0,1997,11,19

In [ ]:
loan=loan[loan["earliest_cr_line_year"]<2016]

In [ ]:
loan

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,settlement_amount,settlement_percentage,settlement_term,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,Scale Technician,9.0,RENT,52000.0,...,NaN,NaN,NaN,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,SDO Supervisor,10.0,OWN,55000.0,...,NaN,NaN,NaN,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,Parole,0.0,MORTGAGE,40000.0,...,NaN,NaN,NaN,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,teacher,10.0,OWN,57000.0,...,NaN,NaN,NaN,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,Machine operator,10.0,OWN,85000.0,...,NaN,NaN,NaN,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,102395624,35000,60 months,13.99,814.21,C3,Industrial Engineer,0.0,MORTGAGE,100000.0,...,NaN,NaN,NaN,2017,4,687.0,772.0,1996,5,20
121171,102426796,12000,60 months,28.69,378.65,F1,foreman,10.0,MORTGAGE,64500.0,...,NaN,NaN,NaN,2017,4,662.0,712.0,2005,11,11
121172,102556443,24000,60 months,23.99,690.30,E2,Senior Escrow Officer,0.0,RENT,107000.0,...,NaN,NaN,NaN,2017,4,672.0,249.5,1995,4,22
121173,102196576,6000,36 months,11.44,197.69,B4,Contact input,5.0,RENT,41000.0,...,NaN,NaN,NaN,2017,4,672.0,717.0,1990,5,26
121174,99799684,30000,60 months,25.49,889.18,E4,Assistant Manager,4.0,MORTGAGE,105700.0,...,NaN,NaN,NaN,2017,4,697.0,577.0,1997,11,19

In [ ]:
loan["earliest_cr_line_year"].value_counts()

earliest_cr_line_year
2005    9538
2006    9218
2004    9192
2003    8113
2007    7130
2002    6923
2001    6357
2000    5699
1999    5118
1998    4075
2008    4051
1997    3772
1996    3590
1995    3359
2011    2864
2010    2848
1994    2788
2009    2714
2012    2633
2013    2407
1993    2373
1990    1687
1992    1635
1991    1570
1989    1534
2014    1310
1987    1169
1988    1157
1986    1000
1985     847
1984     753
1983     614
1982     496
1981     317
1979     293
1978     281
1980     268
1977     234
1976     193
1975     150
2015     142
1974     126
1973     120
1972      99
1969      79
1970      62
1971      55
Name: count, dtype: int64

In [ ]:
loan=loan[loan["last_fico_score"]>0]

In [ ]:
loan

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,settlement_amount,settlement_percentage,settlement_term,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,Scale Technician,9.0,RENT,52000.0,...,NaN,NaN,NaN,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,SDO Supervisor,10.0,OWN,55000.0,...,NaN,NaN,NaN,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,Parole,0.0,MORTGAGE,40000.0,...,NaN,NaN,NaN,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,teacher,10.0,OWN,57000.0,...,NaN,NaN,NaN,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,Machine operator,10.0,OWN,85000.0,...,NaN,NaN,NaN,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,102395624,35000,60 months,13.99,814.21,C3,Industrial Engineer,0.0,MORTGAGE,100000.0,...,NaN,NaN,NaN,2017,4,687.0,772.0,1996,5,20
121171,102426796,12000,60 months,28.69,378.65,F1,foreman,10.0,MORTGAGE,64500.0,...,NaN,NaN,NaN,2017,4,662.0,712.0,2005,11,11
121172,102556443,24000,60 months,23.99,690.30,E2,Senior Escrow Officer,0.0,RENT,107000.0,...,NaN,NaN,NaN,2017,4,672.0,249.5,1995,4,22
121173,102196576,6000,36 months,11.44,197.69,B4,Contact input,5.0,RENT,41000.0,...,NaN,NaN,NaN,2017,4,672.0,717.0,1990,5,26
121174,99799684,30000,60 months,25.49,889.18,E4,Assistant Manager,4.0,MORTGAGE,105700.0,...,NaN,NaN,NaN,2017,4,697.0,577.0,1997,11,19

In [ ]:
loan["last_fico_score"].min()

249.5

In [ ]:
loan=loan[loan["annual_inc"]>0]

In [ ]:
loan=loan[loan["dti"]<=100]

In [ ]:
loan

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,settlement_amount,settlement_percentage,settlement_term,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,Scale Technician,9.0,RENT,52000.0,...,NaN,NaN,NaN,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,SDO Supervisor,10.0,OWN,55000.0,...,NaN,NaN,NaN,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,Parole,0.0,MORTGAGE,40000.0,...,NaN,NaN,NaN,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,teacher,10.0,OWN,57000.0,...,NaN,NaN,NaN,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,Machine operator,10.0,OWN,85000.0,...,NaN,NaN,NaN,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,102395624,35000,60 months,13.99,814.21,C3,Industrial Engineer,0.0,MORTGAGE,100000.0,...,NaN,NaN,NaN,2017,4,687.0,772.0,1996,5,20
121171,102426796,12000,60 months,28.69,378.65,F1,foreman,10.0,MORTGAGE,64500.0,...,NaN,NaN,NaN,2017,4,662.0,712.0,2005,11,11
121172,102556443,24000,60 months,23.99,690.30,E2,Senior Escrow Officer,0.0,RENT,107000.0,...,NaN,NaN,NaN,2017,4,672.0,249.5,1995,4,22
121173,102196576,6000,36 months,11.44,197.69,B4,Contact input,5.0,RENT,41000.0,...,NaN,NaN,NaN,2017,4,672.0,717.0,1990,5,26
121174,99799684,30000,60 months,25.49,889.18,E4,Assistant Manager,4.0,MORTGAGE,105700.0,...,NaN,NaN,NaN,2017,4,697.0,577.0,1997,11,19

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120509 entries, 0 to 121174
Columns: 119 entries, id to credit_history_years
dtypes: float64(50), int64(56), object(13)
memory usage: 110.3+ MB

In [ ]:
loan.columns

Index(['id', 'loan_amnt', 'term', 'int_rate', 'installment', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       ...
       'settlement_amount', 'settlement_percentage', 'settlement_term',
       'issue_year', 'issue_month', 'fico_score', 'last_fico_score',
       'earliest_cr_line_year', 'earliest_cr_line_month',
       'credit_history_years'],
      dtype='object', length=119)

In [ ]:
loan=loan[loan["revol_util"]<=100]

In [ ]:
loan["pct_tl_nvr_dlq"].value_counts()

pct_tl_nvr_dlq
100.0    60863
90.0      1482
90.9      1348
92.3      1346
91.7      1322
         ...
42.4         1
32.3         1
79.7         1
64.4         1
55.8         1
Name: count, Length: 491, dtype: int64

In [ ]:
loan.iloc[:,100:200]

,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,disbursement_method,debt_settlement_flag,settlement_status,settlement_amount,settlement_percentage,settlement_term,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2018,3,762.0,762.0,1998,1,20
1,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2018,3,677.0,677.0,2001,8,16
2,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2018,3,697.0,642.0,2007,3,11
3,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2018,3,682.0,697.0,2000,4,17
4,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2017,4,687.0,772.0,1996,5,20
121171,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2017,4,662.0,712.0,2005,11,11
121172,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2017,4,672.0,249.5,1995,4,22
121173,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2017,4,672.0,717.0,1990,5,26
121174,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,2017,4,697.0,577.0,1997,11,19

In [ ]:
columns=["annual_inc_joint","dti_joint","verification_status_joint","revol_bal_joint","sec_app_fico_range_low","sec_app_fico_range_high","sec_app_inq_last_6mths",
         "sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths",
         "sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","settlement_status","settlement_amount","settlement_percentage",
         "settlement_term"]

In [ ]:
loan.drop(columns=columns,inplace=True)

/tmp/ipykernel_310/4249868854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan.drop(columns=columns,inplace=True)

In [ ]:
loan

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,total_il_high_credit_limit,disbursement_method,debt_settlement_flag,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,Scale Technician,9.0,RENT,52000.0,...,0,Cash,N,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,SDO Supervisor,10.0,OWN,55000.0,...,27751,Cash,N,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,Parole,0.0,MORTGAGE,40000.0,...,118917,Cash,N,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,teacher,10.0,OWN,57000.0,...,35000,Cash,N,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,Machine operator,10.0,OWN,85000.0,...,39733,Cash,N,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121170,102395624,35000,60 months,13.99,814.21,C3,Industrial Engineer,0.0,MORTGAGE,100000.0,...,45802,Cash,N,2017,4,687.0,772.0,1996,5,20
121171,102426796,12000,60 months,28.69,378.65,F1,foreman,10.0,MORTGAGE,64500.0,...,0,Cash,N,2017,4,662.0,712.0,2005,11,11
121172,102556443,24000,60 months,23.99,690.30,E2,Senior Escrow Officer,0.0,RENT,107000.0,...,64422,Cash,N,2017,4,672.0,249.5,1995,4,22
121173,102196576,6000,36 months,11.44,197.69,B4,Contact input,5.0,RENT,41000.0,...,34076,Cash,N,2017,4,672.0,717.0,1990,5,26
121174,99799684,30000,60 months,25.49,889.18,E4,Assistant Manager,4.0,MORTGAGE,105700.0,...,89732,Cash,N,2017,4,697.0,577.0,1997,11,19

In [ ]:
loan["loan_status"].value_counts(normalize=True)

loan_status
0    0.781751
1    0.218249
Name: proportion, dtype: float64

In [ ]:
loan_2017 = loan[loan["issue_year"] == 2017]
loan_2018 = loan[loan["issue_year"] == 2018]

In [ ]:
loan.to_excel("/content/drive/MyDrive/Colab/loan project/loan5.xlsx",index=False)

In [ ]:
loan_2017

NameError: name 'loan_2017' is not defined

In [ ]:
loan=pd.read_excel("/content/drive/MyDrive/Colab/loan project/loan5.xlsx")

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120092 entries, 0 to 120091
Data columns (total 99 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              120092 non-null  int64
 1   loan_amnt                       120092 non-null  int64
 2   term                            120092 non-null  object
 3   int_rate                        120092 non-null  float64
 4   installment                     120092 non-null  float64
 5   sub_grade                       120092 non-null  object
 6   emp_length                      111581 non-null  float64
 7   home_ownership                  120092 non-null  object
 8   annual_inc                      120092 non-null  float64
 9   verification_status             120092 non-null  object
 10  loan_status                     120092 non-null  int64
 11  Purpose                         120092 non-null  object
 12  addr_state                      120092 non-null  object
 13  dti                             120092 non-null  float64
 14  delinq_2yrs                     120092 non-null  int64
 15  inq_last_6mths                  120092 non-null  int64
 16  mths_since_last_delinq          59299 non-null   float64
 17  mths_since_last_record          22047 non-null   float64
 18  open_acc                        120092 non-null  int64
 19  pub_rec                         120092 non-null  int64
 20  revol_bal                       120092 non-null  int64
 21  revol_util                      120092 non-null  float64
 22  total_acc                       120092 non-null  int64
 23  initial_list_status             120092 non-null  object
 24  out_prncp                       120092 non-null  float64
 25  total_pymnt                     120092 non-null  float64
 26  total_rec_prncp                 120092 non-null  float64
 27  total_rec_int                   120092 non-null  float64
 28  total_rec_late_fee              120092 non-null  float64
 29  recoveries                      120092 non-null  float64
 30  collection_recovery_fee         120092 non-null  float64
 31  last_pymnt_amnt                 120092 non-null  float64
 32  collections_12_mths_ex_med      120092 non-null  int64
 33  mths_since_last_major_derog     32568 non-null   float64
 34  application_type                120092 non-null  object
 35  acc_now_delinq                  120092 non-null  int64
 36  tot_coll_amt                    120092 non-null  int64
 37  tot_cur_bal                     120092 non-null  int64
 38  open_acc_6m                     120092 non-null  int64
 39  open_act_il                     120092 non-null  int64
 40  open_il_12m                     120092 non-null  int64
 41  open_il_24m                     120092 non-null  int64
 42  mths_since_rcnt_il              116845 non-null  float64
 43  total_bal_il                    120092 non-null  int64
 44  il_util                         103310 non-null  float64
 45  open_rv_12m                     120092 non-null  int64
 46  open_rv_24m                     120092 non-null  int64
 47  max_bal_bc                      120092 non-null  int64
 48  all_util                        120092 non-null  int64
 49  total_rev_hi_lim                120092 non-null  int64
 50  inq_fi                          120092 non-null  int64
 51  total_cu_tl                     120092 non-null  int64
 52  inq_last_12m                    120092 non-null  int64
 53  acc_open_past_24mths            120092 non-null  int64
 54  avg_cur_bal                     120092 non-null  int64
 55  bc_open_to_buy                  118542 non-null  float64
 56  bc_util                         118486 non-null  float64
 57  chargeoff_within_12_mths        120092 non-null  int64
 58  delinq_amnt                     120092 non-null  int64
 59  mo_sin_old_il_acct              116845 non-null  float64
 60  mo_sin_old_rev_tl_op            120092 non-null  int64
 61  mo_sin_rcnt_rev_tl_op           120092 non-null  int64
 62  mo_sin_rcnt_tl                  120092 non-null  int64
 63  mort_acc                        120092 non-null  int64
 64  mths_since_recent_bc            118637 non-null  float64
 65  mths_since_recent_bc_dlq        27666 non-null   float64
 66  mths_since_recent_inq           109635 non-null  float64
 67  mths_since_recent_revol_delinq  39985 non-null   float64
 68  num_accts_ever_120_pd           120092 non-null  int64
 69  num_actv_bc_tl                  120092 non-null  int64
 70  num_actv_rev_tl                 120092 non-null  int64
 71  num_bc_sats                     120092 non-null  int64
 72  num_bc_tl                       120092 non-null  int64
 73  num_il_tl                       120092 non-null  int64
 74  num_op_rev_tl                   120092 non-null  int64
 75  num_rev_accts                   120092 non-null  int64
 76  num_rev_tl_bal_gt_0             120092 non-null  int64
 77  num_sats                        120092 non-null  int64
 78  num_tl_120dpd_2m                114867 non-null  float64
 79  num_tl_30dpd                    120092 non-null  int64
 80  num_tl_90g_dpd_24m              120092 non-null  int64
 81  num_tl_op_past_12m              120092 non-null  int64
 82  pct_tl_nvr_dlq                  120091 non-null  float64
 83  percent_bc_gt_75                118539 non-null  float64
 84  pub_rec_bankruptcies            120092 non-null  int64
 85  tax_liens                       120092 non-null  int64
 86  tot_hi_cred_lim                 120092 non-null  int64
 87  total_bal_ex_mort               120092 non-null  int64
 88  total_bc_limit                  120092 non-null  int64
 89  total_il_high_credit_limit      120092 non-null  int64
 90  disbursement_method             120092 non-null  object
 91  debt_settlement_flag            120092 non-null  object
 92  issue_year                      120092 non-null  int64
 93  issue_month                     120092 non-null  int64
 94  fico_score                      120092 non-null  float64
 95  last_fico_score                 120092 non-null  float64
 96  earliest_cr_line_year           120092 non-null  int64
 97  earliest_cr_line_month          120092 non-null  int64
 98  credit_history_years            120092 non-null  int64
dtypes: float64(31), int64(58), object(10)
memory usage: 90.7+ MB

In [ ]:
loan1.to_csv("/content/drive/MyDrive/Colab/loan project/loan5.csv",index=False)

In [2]:
loan1 = pd.read_csv("/content/drive/MyDrive/Colab/loan project/loan5.csv")

In [ ]:
loan1["acc_now_delinq"].value_counts()

acc_now_delinq
0    119643
1       412
2        21
3         2
Name: count, dtype: int64

In [ ]:
loan1["inq_last_6mths"].value_counts()

inq_last_6mths
0    71988
1    32512
2    11049
3     3471
4      773
5      299
Name: count, dtype: int64

In [4]:
loan1["inq_last_6mths"].value_counts()

inq_last_6mths
0    71978
1    32510
2    11048
3     3470
4      773
5      299
Name: count, dtype: int64

In [ ]:
loan1 = loan1[~loan1["home_ownership"].isin(["NONE", "ANY"])]

In [ ]:
loan1

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,total_il_high_credit_limit,disbursement_method,debt_settlement_flag,issue_year,issue_month,fico_score,last_fico_score,earliest_cr_line_year,earliest_cr_line_month,credit_history_years
0,130956066,3000,36 months,7.34,93.10,A4,9.0,RENT,52000.0,Source Verified,...,0,Cash,N,2018,3,762.0,762.0,1998,1,20
1,130968727,5000,36 months,11.98,166.03,B5,10.0,OWN,55000.0,Not Verified,...,27751,Cash,N,2018,3,677.0,677.0,2001,8,16
2,130910225,7000,36 months,11.98,232.44,B5,0.0,MORTGAGE,40000.0,Verified,...,118917,Cash,N,2018,3,697.0,642.0,2007,3,11
3,130966492,30000,36 months,21.85,1143.39,D5,10.0,OWN,57000.0,Verified,...,35000,Cash,N,2018,3,682.0,697.0,2000,4,17
4,130942737,21000,60 months,20.39,560.94,D4,10.0,OWN,85000.0,Source Verified,...,39733,Cash,N,2018,3,667.0,657.0,2008,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120087,102395624,35000,60 months,13.99,814.21,C3,0.0,MORTGAGE,100000.0,Source Verified,...,45802,Cash,N,2017,4,687.0,772.0,1996,5,20
120088,102426796,12000,60 months,28.69,378.65,F1,10.0,MORTGAGE,64500.0,Not Verified,...,0,Cash,N,2017,4,662.0,712.0,2005,11,11
120089,102556443,24000,60 months,23.99,690.30,E2,0.0,RENT,107000.0,Source Verified,...,64422,Cash,N,2017,4,672.0,249.5,1995,4,22
120090,102196576,6000,36 months,11.44,197.69,B4,5.0,RENT,41000.0,Source Verified,...,34076,Cash,N,2017,4,672.0,717.0,1990,5,26
120091,99799684,30000,60 months,25.49,889.18,E4,4.0,MORTGAGE,105700.0,Verified,...,89732,Cash,N,2017,4,697.0,577.0,1997,11,19

In [12]:
loan1["mths_since_recent_bc"].value_counts(dropna=False)
print("mths_since_recent_bc",loan1["mths_since_recent_bc"].isna().sum())

print("percent_bc_gt_75",loan1["percent_bc_gt_75"].isna().sum())
print("bc_util",loan1["bc_util"].isna().sum())
print("mths_since_rcnt_il",loan1["mths_since_rcnt_il"].isna().sum())
print("mo_sin_old_il_acct",loan1["mo_sin_old_il_acct"].isna().sum())
print("num_tl_120dpd_2m",loan1["num_tl_120dpd_2m"].isna().sum())
print("emp_length",loan1["emp_length"].isna().sum())
print("mths_since_recent_inq",loan1["mths_since_recent_inq"].isna().sum())
print("il_util",loan1["il_util"].isna().sum())

mths_since_recent_bc 1454
bc_open_to_buy 1549
percent_bc_gt_75 1552
bc_util 1605
mths_since_rcnt_il 3246
mo_sin_old_il_acct 3246
num_tl_120dpd_2m 5225
emp_length 8506
mths_since_recent_inq 10452
il_util 16780

In [24]:
print(loan1["bc_open_to_buy"].value_counts())
loan1["bc_open_to_buy"].isna().sum()

bc_open_to_buy
0.0        916
2000.0     131
5000.0     115
500.0      113
1000.0     106
          ...
19746.0      1
47021.0      1
25032.0      1
52223.0      1
12427.0      1
Name: count, Length: 37297, dtype: int64

np.int64(1549)

In [29]:
loan1["il_util"].value_counts(dropna=False)

il_util
NaN      16780
83.0      2163
81.0      2069
78.0      2041
86.0      1969
         ...
196.0        1
182.0        1
199.0        1
181.0        1
176.0        1
Name: count, Length: 202, dtype: int64

In [30]:
cols=['il_util',
'mths_since_recent_inq',
'emp_length',
'num_tl_120dpd_2m',
'mo_sin_old_il_acct',
'mths_since_rcnt_il',
'bc_util',
'percent_bc_gt_75',
'bc_open_to_buy',
'mths_since_recent_bc',
'pct_tl_nvr_dlq']
loan1[cols].skew()

il_util                  -0.332471
mths_since_recent_inq     0.993904
emp_length               -0.155660
num_tl_120dpd_2m         46.378270
mo_sin_old_il_acct        0.304497
mths_since_rcnt_il        3.734626
bc_util                  -0.009136
percent_bc_gt_75          0.616984
bc_open_to_buy            3.280001
mths_since_recent_bc      3.944302
pct_tl_nvr_dlq           -2.345472
dtype: float64

In [ ]:
import warnings
import pandas as pd
warnings.simplefilter(action='ignore', category=pd.errors.DtypeWarning)

main=pd.read_csv("/content/drive/MyDrive/Colab/loan project/accepted_2007_to_2018Q4.csv")

In [1]:
main

NameError: name 'main' is not defined